spring.application.name=lista-contatos
spring.datasource.url=jdbc:mysql://localhost:3306/listaContatos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysqlPW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
